# Change the default port if 8080 is taken
server.port=8282

# Application metadata
spring.application.name=marketplace-backend

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5438/marketplace-backend
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties to ensure it initializes smoothly
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate Settings
# 'update' automatically creates/updates database tables based on your Java entities
spring.jpa.hibernate.ddl-auto=update
# Logs the SQL queries to your console (great for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true