### Get
GET http://127.0.0.1:8282/products

### Create product
POST http://127.0.0.1:8282/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Description of Product 1",
  "price": 19.99
}